### ISSUE TITLE
automatic scrolling has some issue

### ISSUE THREAD

**Issue by AbeyHurtis** [hiamandeep/speedcoder-keyboard-layouts#8]
some times it scrolls down before the current part we are typing is not done thus not being able to see what we are typing

**Comment by schaefer-dev** [comment]
Can confirm, this issue seems to make long files basically impossible to type as you are constantly forced to scroll back up manually

**Comment by hiamandeep** [comment]
This is fixed now. please check.
There should be no problem if the code is less than 350 lines.
